checks:
  javascript:
    code_rating: true
    duplicate_code: true

build:
  environment:
    node: v8.9.0
  
  project_setup:
    before:
      - cd front

  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run

filter:
  excluded_paths:
    - 'api/*'
    - 'front/config/*'
    - 'front/coverage/*'
    - 'front/node_modules/*'
    - 'front/public/*'
    - 'front/scripts/*'
    - 'front/static/*'
    - 'front/src/**/*.spec.js'
    - 'front/src/**/*.test.js'
    - 'front/src/registerServiceWorker.js'
    - 'front/src/setupTests.js'
