export const FETCH_FILTER_DATA_START = 'FETCH_FILTER_DATA_START';
export const FETCH_FILTER_DATA_SUCCESS = 'FETCH_FILTER_DATA_SUCCESS';
export const FETCH_FILTER_DATA_FAILURE = 'FETCH_FILTER_DATA_FAILURE';

export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const RESET_MOVIES = 'RESET_MOVIES';

export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';

export const FILTERS_INIT = 'FILTERS_INIT';
export const TOGGLE_FILTERS_PANEL = 'TOGGLE_FILTERS_PANEL';

export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const HANDLE_FILTERS_INPUT = 'HANDLE_FILTERS_INPUT';
export const HANDLE_RANGE_INPUT = 'HANDLE_RANGE_INPUT';

export const SORT_ALPHA_DESC = 'SORT_ALPHA_DESC';
export const SORT_ALPHA_ASC = 'SORT_ALPHA_ASC';

export default {
  FETCH_FILTER_DATA_START,
  FETCH_FILTER_DATA_SUCCESS,
  FETCH_FILTER_DATA_FAILURE,
  FETCH_MOVIES_START,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIES_FAILURE,
  RESET_MOVIES,
  FETCH_MOVIE_SUCCESS,
  TOGGLE_FILTERS_PANEL,
  FILTERS_INIT,
  SORT_ALPHA_DESC,
  SORT_ALPHA_ASC,
  CLEAR_FILTERS,
  FILTER_MOVIES,
  HANDLE_RANGE_INPUT,
  HANDLE_FILTERS_INPUT
};
