export const FETCH_FILTER_DATA_START = 'FETCH_FILTER_DATA_START';
export const FETCH_FILTER_DATA_SUCCESS = 'FETCH_FILTER_DATA_SUCCESS';
export const FETCH_FILTER_DATA_FAILURE = 'FETCH_FILTER_DATA_FAILURE';

export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const RESET_MOVIES = 'RESET_MOVIES';

export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';

export const FETCH_TV_SUCCESS = 'FETCH_TV_SUCCESS';

export const FILTERS_INIT = 'FILTERS_INIT';
export const TOGGLE_FILTERS_PANEL = 'TOGGLE_FILTERS_PANEL';

export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const HANDLE_FILTERS_INPUT = 'HANDLE_FILTERS_INPUT';
export const HANDLE_RANGE_INPUT = 'HANDLE_RANGE_INPUT';

export const SORT_ALPHA_DESC = 'SORT_ALPHA_DESC';
export const SORT_ALPHA_ASC = 'SORT_ALPHA_ASC';

export const NOTIFY_STREAM_MESSAGE = 'NOTIFY_STREAM_MESSAGE';
export const REMOVE_NOTIF_BY_ID = 'REMOVE_NOTIF_BY_ID';

export const USER_LOGGING_IN = 'USER_LOGGING_IN';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const FETCH_LIBRARIES = 'FETCH_LIBRARIES';
export const ADD_LIBRARY = 'ADD_LIBRARY';
export const DELETE_LIBRARY = 'DELETE_LIBRARY';

export const USER_EDIT = 'USER_EDIT';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_FETCH_START = 'USER_FETCH_START';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';

export default {
  FETCH_FILTER_DATA_START,
  FETCH_FILTER_DATA_SUCCESS,
  FETCH_FILTER_DATA_FAILURE,
  FETCH_MOVIES_START,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIES_FAILURE,
  RESET_MOVIES,
  FETCH_MOVIE_SUCCESS,
  FETCH_TV_SUCCESS,
  TOGGLE_FILTERS_PANEL,
  FILTERS_INIT,
  SORT_ALPHA_DESC,
  SORT_ALPHA_ASC,
  CLEAR_FILTERS,
  FILTER_MOVIES,
  HANDLE_RANGE_INPUT,
  HANDLE_FILTERS_INPUT,
  NOTIFY_STREAM_MESSAGE,
  REMOVE_NOTIF_BY_ID,
  USER_LOGGING_IN,
  USER_LOGGED_IN,
  USER_LOGGED_OUT,
  FETCH_LIBRARIES,
  ADD_LIBRARY,
  DELETE_LIBRARY,
  USER_EDIT,
  USER_FAILURE,
  USER_FETCH_START,
  USER_FETCH_SUCCESS,
  USER_FETCH_FAILURE,
  USER_CREATE_SUCCESS,
  USER_UPDATE_SUCCESS,
  USER_DELETE_SUCCESS
};
